development:
  adapter: postgresql
  database: ror_campinapolis_policia_development
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: ror_campinapolis_policia_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: ror_campinapolis_policia_production
  pool: 5
  timeout: 5000
